{
 "title": "Drupal",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Requests time",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (le) (rate(drupal_http_requests_bucket[30s]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "User count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 0 },
   "targets": [
    { "expr": "drupal_user_count_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Node count per bundle",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 0 },
   "targets": [
    {
     "expr": "drupal_node_count_total_per_bundle",
     "legendFormat": "{{bundle}}"
    }
   ]
  },
  {
   "title": "Drupal log distribution",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (level) (count_over_time({job=\"drupal\"}[5m]))",
     "legendFormat": "{{ level }}",
     "resolution": 1
    }
   ]
  },
  {
   "title": "Drupal logs",
   "type": "logs",
   "gridPos": { "h": 18, "w": 15, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "{job=\"drupal\"} |= `` | json"
    }
   ]
  },
  {
   "title": "Microservice logs",
   "type": "logs",
   "gridPos": { "h": 18, "w": 9, "x": 15, "y": 15 },
   "targets": [
    {
     "expr": "{job=\"microservice\"} |= `` | json"
    }
   ]
  }
 ]
}