# config file version
apiVersion: 1

datasources:
- name: Loki-drupal
  type: loki
  enabled: true
  access: proxy
  orgId: 1
  uid: loki_drupal
  editable: true
  isDefault: false
  url: http://loki:3100
  jsonData:
    derivedFields:
      - datasourceUid: tempo
        matcherRegex: "{.*\"traceID\":\"(.*)\",\"referer.*}"
        name: TraceID
        url: ${__value.raw}
