# config file version
apiVersion: 1

datasources:
- name: Prometheus
  type: prometheus
  enabled: true
  access: proxy
  orgId: 1
  uid: prometheus
  editable: true
  isDefault: false
  url: http://prometheus:9090
  jsonData:
    httpMethod: POST
