include:
  # Best practice is to pin to a tag or a SHA1. https://docs.gitlab.com/ee/ci/yaml/#includefile
  # Since composer-plugin is remote for now, we use include:remote
  - remote: 'https://gitlab.com/drupalspoons/composer-plugin/-/raw/2.2.0/templates/.gitlab-ci.yml'
  #- project: 'drupalspoons/composer-plugin'
    #ref: "2.2.0"
    # The template below may be inspected at https://gitlab.com/drupalspoons/composer-plugin/-/blob/master/templates/.gitlab-ci.yml
    #file: 'templates/.gitlab-ci.yml'

variables:
  # Run tests on Drupal 9.x by default.
  # https://getcomposer.org/doc/articles/versions.md#next-significant-release-operators
  DRUPAL_CORE_CONSTRAINT: ~9.1.0

#
# Projects may override anything in the template above.
# The code below is specific to devel project. Comment it out or delete it when
# copying this file to your new project.
#

# Include a phpspec/prophecy-phpunit requirement.
composer_node:
  after_script:
    # See https://www.drupal.org/project/drupal/issues/3182653
    # This will fail on PHPUnit 8-, that is OK as its not needed there.
    - vendor/bin/spoon require --no-progress phpspec/prophecy-phpunit:^2 || true


# Add /webprofiler to ignored paths.
phpcs:
  script:
    - PWD=$(pwd) && vendor/bin/phpcs --runtime-set ignore_warnings_on_exit 1 --runtime-set ignore_errors_on_exit 1 --ignore=$PWD/web/,$PWD/vendor/,$PWD/webprofiler/ --report-junit=junit.xml --report-full --report-summary

