receivers:
  otlp:
    protocols:
      http:

processors:
  batch:

exporters:
  otlphttp:
    endpoint: http://tempo:4318
  logging:
    logLevel: debug

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp,logging]
