version: '3.6'
services:
  grafana-agent:
    container_name: ddev-${DDEV_PROJECT}-grafana-agent
    entrypoint:
      - /bin/agent
      - -config.file=/mnt/ddev_config/grafana/agent/agent-config.yaml
      - -metrics.wal-directory=/tmp/agent/wal
      - -server.http-listen-address=127.0.0.1
      - -server.http-listen-port=12345
    hostname: ${DDEV_PROJECT}-grafana-agent
    image: grafana/agent
    expose:
      - '12345'
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    environment:
      - VIRTUAL_HOST=$DDEV_HOSTNAME
      - HTTP_EXPOSE=12345:12345
      - HTTPS_EXPOSE=12346:12345
    volumes:
      - '.:/mnt/ddev_config'
      - '../:/var/www/html'
